# Generated by Django 6.0 on 2025-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='electrodomestico', max_length=255),
            preserve_default=False,
        ),
    ]
