# Generated by Django 6.0 on 2025-12-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='discount',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
